version: "3.8"

services:
  bedouidb:
    image: mysql:8.0
    container_name: bedouidb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: eventsProject
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  backend-spring:
    container_name: backend-spring
    image: docker.io/bedouimohamed/bedoui:latest
    build:
      context: ./src
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://bedouidb:3306/eventsProject?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8087:8087"
    depends_on:
      - bedouidb
    restart: on-failure
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    depends_on:
      - backend-spring
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mynetwork

volumes:
  mysql-data:
  grafana:
  prometheus-data:

networks:
  mynetwork:
    driver: bridge
