version: "3.8"

services:
  backend-spring:
    container_name: backend-spring
    image: docker.io/esprit11/tpfoyer-app:latest
    build:
      context: src
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://EventDB:3306/tpFoyer17?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8087:8087"  # Port mapping for backend Spring Boot
    depends_on:
      - db
    restart: on-failure
    networks:
      - mynetwork


  db:
    container_name: db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: tpFoyer17
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork


  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    depends_on:
      - backend-spring
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana


    depends_on:
      - prometheus




volumes:
  mysql-data:
  grafana:
  prometheus-data:

networks:
  mynetwork:
    driver: bridge